# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-15 22:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tienda.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caracteristica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caracteristica', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Caracteristica_Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default='', max_length=50)),
                ('valor', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(blank=True, default='', max_length=100)),
                ('estado', models.BooleanField(default=True)),
                ('caracteristica', models.ManyToManyField(to='tienda.Caracteristica')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1, null=True)),
                ('anotaciones', models.CharField(blank=True, default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1, null=True)),
                ('precio_costo', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido_Ingreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateTimeField(auto_now=True)),
                ('descripcion', models.CharField(blank=True, default='', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default='', max_length=200)),
                ('descripcion', models.CharField(blank=True, default='', max_length=250)),
                ('precio_costo', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('stock', models.IntegerField(default=0, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('imagen', models.ImageField(blank=True, upload_to=tienda.models.Producto.upload_path_handler)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.Categoria')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.Marca')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateTimeField(auto_now=True)),
                ('descripcion', models.CharField(blank=True, default='', max_length=250)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('estado', models.BooleanField(default=True)),
                ('detalle_venta', models.ManyToManyField(through='tienda.DetalleVenta', to='tienda.Producto')),
            ],
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='detalle_venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.Venta'),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.Producto'),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='pedido_ingreso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalle_pedido', to='tienda.Pedido_Ingreso'),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tienda.Producto'),
        ),
        migrations.AddField(
            model_name='caracteristica_articulo',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caracteristica_articulo', to='tienda.DetallePedido'),
        ),
    ]
