# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-18 23:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0011_auto_20180217_2054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalleventa',
            old_name='producto',
            new_name='producto_pedido',
        ),
    ]
