# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-18 23:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0012_auto_20180218_1715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalleventa',
            old_name='producto_pedido',
            new_name='producto',
        ),
    ]
