# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-18 23:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0013_auto_20180218_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalleventa',
            old_name='venta',
            new_name='detalle_venta',
        ),
    ]
