# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-18 23:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0015_auto_20180218_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='detalle_pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detallepedido', to='tienda.DetallePedido'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='detalle_venta',
            field=models.ManyToManyField(related_name='detalleventa', through='tienda.DetalleVenta', to='tienda.DetallePedido'),
        ),
    ]
