# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-19 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0016_auto_20180218_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venta_detalle', to='tienda.Venta'),
        ),
    ]
