# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-26 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0017_auto_20180219_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido_ingreso',
            name='fecha_ingreso',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha_venta',
            field=models.DateField(auto_now=True),
        ),
    ]
